name: Set up build environment
description: Set up Java and Gradle.

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Cache Xtext ANTLR generator
      uses: actions/cache@v4
      with:
        path: lfc/core/.antlr-generator-3.2.0-patch.jar
        key: antlr-generator-3.2.0-patch
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.8.0
