USEMODULE += ztimer64
USEMODULE += ztimer64_usec
USEMODULE += nanopb
USEMODULE += proto

# If Feature NETWORK_CHANNEL_TCP_POSIX is enabled
ifeq ($(filter -DNETWORK_CHANNEL_TCP_POSIX, $(CFLAGS)), -DNETWORK_CHANNEL_TCP_POSIX)
  # Enable networking
  USEMODULE += netdev_default
  USEMODULE += auto_init_gnrc_netif

  # Enable sockets
  USEMODULE += gnrc_ipv6_default
  USEMODULE += sock_tcp
  USEMODULE += posix_sockets
  USEMODULE += posix_sleep
  USEMODULE += posix_inet

  # Enable posix threads
  ifneq ($(BOARD),native)
    USEMODULE += pthread
  endif
endif

# If Feature NETWORK_CHANNEL_COAP is enabled
ifeq ($(filter -DNETWORK_CHANNEL_COAP, $(CFLAGS)), -DNETWORK_CHANNEL_COAP)
  # Enable networking
  USEMODULE += netdev_default
  USEMODULE += auto_init_gnrc_netif
  USEMODULE += gnrc_ipv6_default

  # Enable coap
  USEMODULE += gcoap
endif

ifeq ($(filter -DNETWORK_CHANNEL_UART, $(CFLAGS)), -DNETWORK_CHANNEL_UART)
  USEMODULE += periph_uart
endif
