name: Install FlexPRET dependencies
description: Install FlexPRET dependencies
runs:
  using: "composite"
  steps:
    - name: Clone FlexPRET
      uses: actions/checkout@v3
      with:
        repository: pretis/flexpret
        path: flexpret
        submodules: recursive
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.8
    - name: Install dependencies
      run: sudo apt install verilator cmake -y
      shell: bash
    - name: Cache riscv-none-elf-gcc
      id: cache-gcc
      uses: actions/cache@v4
      with:
        path: /opt/xpack-riscv-none-elf-gcc-14.2.0-2
        key: flexpret-gcc-${{ runner.os }}

    - name: Install riscv-none-elf-gcc
      if: steps.cache-gcc.outputs.cache-hit != 'true'
      run: |
        wget -q --show-progress https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v14.2.0-2/xpack-riscv-none-elf-gcc-14.2.0-2-linux-x64.tar.gz -O gcc.tar.gz
        tar xvf gcc.tar.gz --directory=/opt
      shell: bash

    - name: Build emulator and SDK
      run: |
        cd flexpret
        source env.bash
        cmake -Bbuild 
        cd build 
        make all install 
      shell: bash
    - name: Set environmental variables
      run: |
        echo "PATH=$PATH:$PWD/flexpret/build/emulator" >> $GITHUB_ENV
        echo "FP_PATH=$PWD/flexpret" >> $GITHUB_ENV
        echo "FP_SDK_PATH=$PWD/flexpret/sdk" >> $GITHUB_ENV
        echo "RISCV_TOOL_PATH_PREFIX=/opt/xpack-riscv-none-elf-gcc-14.2.0-2" >> $GITHUB_ENV
      shell: bash


