CFLAGS += -DPLATFORM_RIOT=1

# Use an immediate variable to evaluate `MAKEFILE_LIST` now
USEMODULE_INCLUDES_proto := $(LAST_MAKEFILEDIR)/../../../../external
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_proto)