name: Install Patmos (self-hosted)
description: Install Patmos and dependencies for self-hosted runners (no sudo)
inputs:
  clone-template:
    description: "Clone lf-patmos-template next to reactor-uc"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Clone and build Patmos
      shell: bash
      run: |
        if [ -d "$HOME/t-crest" ]; then
          echo "t-crest already exists; skipping Patmos build"
          exit 0
        fi
        export PATH=$PATH:$HOME/t-crest/local/bin
        echo "PATH=$PATH:$HOME/t-crest/local/bin" >> "$GITHUB_ENV"
        echo $PATH
        mkdir -p ~/t-crest
        cd ~/t-crest
        git clone https://github.com/t-crest/patmos-misc.git misc
        ./misc/build.sh -q
      
    - name: Verify Patmos installation
      shell: bash
      run: |
        patmos-clang --version
        if [ $? -ne 0 ]; then
          echo "Patmos installation failed"
          exit 1
        fi

    - name: Clone template
      shell: bash
      run: |
        if [ -d "$GITHUB_WORKSPACE/../lf-patmos-template" ]; then
          echo "lf-patmos-template already exists; skipping clone"
          exit 0
        fi
        if [ "${{ inputs.clone-template }}" = "true" ]; then
          echo "Cloning lf-patmos-template (reactor-uc branch) as sibling of reactor-uc..."
          # Clone one level up from GITHUB_WORKSPACE (which is reactor-uc/)
          cd "$GITHUB_WORKSPACE/.."
          git clone --depth=1 --branch reactor-uc https://github.com/lf-lang/lf-patmos-template.git lf-patmos-template
          if [ ! -f "$GITHUB_WORKSPACE/../lf-patmos-template/MakefileTemplate" ]; then
            echo "lfc: error: Patmos template not found at: $GITHUB_WORKSPACE/../lf-patmos-template/MakefileTemplate";
            exit 1;
          fi
          echo "Template cloned successfully at $GITHUB_WORKSPACE/../lf-patmos-template"
        fi
