name: Install and build RIOT dependencies
description: Install and build RIOT dependencies
runs:
  using: "composite"
  steps:
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install tmux
      shell: bash

    - name: Cache RIOT
      id: cache-riot
      uses: actions/cache@v4
      with:
        path: ${{env.RIOTBASE}}
        key: riot-${{env.RIOT_COMMIT_ID}}

    - name: Install RIOT
      if: steps.cache-riot.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/RIOT-OS/RIOT.git ${{env.RIOTBASE}}
        cd ${{env.RIOTBASE}}
        git checkout ${{env.RIOT_COMMIT_ID}}
      shell: bash
