name: Install and build RIOT dependencies
description: Install and build RIOT dependencies
runs:
  using: "composite"
  steps:
    - name: Cache RIOT
      id: cache-riot
      uses: actions/cache@v4
      with:
        path: /opt/RIOT-${{env.RIOT_VERSION}}
        key: riot-${{env.RIOT_VERSION}}

    - name: Install RIOT
      if: steps.cache-riot.outputs.cache-hit != 'true'
      run: |
        wget -q "https://github.com/RIOT-OS/RIOT/archive/refs/tags/${{env.RIOT_VERSION}}.tar.gz"
        tar xvf "${{env.RIOT_VERSION}}.tar.gz" --directory /opt/
      shell: bash
