name: Install and build Zephyr dependencies
description: Install and build Zephyr dependencies
runs:
  using: "composite"
  steps:
    - name: Setup environment variables
      run: |
        echo "SDK_VERSION=0.16.8" >> $GITHUB_ENV
      shell: bash
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
      shell: bash
    - name: Install West
      run: pip install west
      shell: bash

    - name: Cache SDK
      id: cache-zephyr-sdk
      uses: actions/cache@v4
      with:
        path: /opt/zephyr-sdk-${{env.SDK_VERSION}}
        key: zephyr-sdk-${{env.SDK_VERSION}}-${{ runner.os }}

    - name: Install Zephyr SDK
      if: steps.cache-zephyr-sdk.outputs.cache-hit != 'true'
      run : |
        wget -q "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${{env.SDK_VERSION}}/zephyr-sdk-${{env.SDK_VERSION}}_linux-x86_64.tar.xz"
        wget -O - "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${{env.SDK_VERSION}}/sha256.sum" | shasum --check --ignore-missing
        sudo tar xvf "zephyr-sdk-${{env.SDK_VERSION}}_linux-x86_64.tar.xz" --directory /opt/
      shell: bash

    - name: Cache Zephyr RTOS
      id: cache-zephyr-rtos
      uses: actions/cache@v4
      with:
        path: /opt/lf-west-template
        key: lf-west-template-${{ runner.os }}
  
    - name: Download and install Zephyr RTOS with the lf-west-template
      if: steps.cache-zephyr-rtos.outputs.cache-hit != 'true'
      run: |
          cd /opt
          git clone https://github.com/lf-lang/lf-west-template && cd lf-west-template
          west update
      shell: bash
    - name: Setup environment variables
      run: |
          cd "/opt/zephyr-sdk-${{env.SDK_VERSION}}"
          sudo ./setup.sh -t all -h -c
          echo "ZEPHYR_BASE=/opt/lf-west-template/deps/zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk-${{env.SDK_VERSION}}/" >> $GITHUB_ENV
          cd /opt/lf-west-template
          west zephyr-export
          pip install -r deps/zephyr/scripts/requirements.txt
      shell: bash