name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  issues: write
  pull-requests: write

env:
  REACTOR_UC_PATH: ${{ github.workspace }}

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt-get install -y pipx lcov
          sudo pipx install clang-tidy

      - uses: ./.github/actions/setup-lf-tests

      - name: Run coverage (also runs tests)
        run: make coverage CMAKE_EXTRA_FLAGS=-DLF_SKIP_GENERATE=ON

      - name: Publish coverage results
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
        with:
          lcov-file: build/coverage.info
          delete-old-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  macos-build:
    name: macos build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps
        run: brew install coreutils

      - uses: ./.github/actions/setup-lf-tests

      - name: Unit + LF tests
        run: make unit-test-lf-test CMAKE_EXTRA_FLAGS=-DLF_SKIP_GENERATE=ON
