name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  formating:
    name: formating
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install deps
        run: |
          sudo apt-get install pipx -y
          sudo pipx install clang-format clang-tidy
      - name: Setup java and gradle for compiling lfc
        uses: ./.github/actions/lingua-franca
      - name: Runtime format check
        run: |
          clang-format --version
          make format-check
      - name: LFC format check
        run: cd lfc && ./gradlew spotlessCheck
